# Generated by Django 4.2.7 on 2024-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("student", "Student"), ("teacher", "Teacher"), ("admin", "Admin")],
                default="admin",
                max_length=50,
                verbose_name="user type",
            ),
        ),
    ]
