# Generated by Django 4.1.6 on 2023-07-12 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_studentprofile_study_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_profile",
                to="accounts.admin",
            ),
        ),
        migrations.AlterField(
            model_name="otpnumber",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the OTP number has been verified by the user",
                verbose_name="verified",
            ),
        ),
        migrations.AlterField(
            model_name="otpnumber",
            name="number",
            field=models.CharField(
                help_text="The OTP number sent to the user", max_length=16, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="otpnumber",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user associated with the OTP number",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_number",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="otpnumber",
            name="valid_until",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The timestamp of the moment of expiry of the saved number.",
                verbose_name="valid until",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="user",
            name="identification",
            field=models.IntegerField(blank=True, null=True, verbose_name="identification"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="phone_number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="state"),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="street"),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Student", "student"), ("Teacher", "teacher"), ("Admin", "admin")],
                default="Admin",
                max_length=50,
                verbose_name="user type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zipcode",
            field=models.IntegerField(blank=True, null=True, verbose_name="zipcode"),
        ),
    ]
