# Specify the version of the docker-compose file format
version: "3.9"

# Define the services that make up your application
services:
  db:
    # Use the postgres:15-alpine image from Docker Hub
    image: postgres:15.3-alpine

    # Restart the container unless it is stopped by the user
    restart: unless-stopped

    # Expose port 5432 on the host and map it to port 5432 on the container
    ports:
      - "5432:5432"

    # Set environment variables for the database configuration
    environment:
      POSTGRES_DB: dauth
      POSTGRES_USER: dauth
      POSTGRES_PASSWORD: dauth

    # Mount a named volume to persist the database data
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  backend:
    container_name: backend_container

    # Use the backend image that is built from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - ./.envs/.env.dev

    # Mount a named volume to persist the backend django project
    volumes:
      - static_data:/backend/src/static
      - media_data:/backend/media

    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile

    volumes:
      - static_data:/backend/src/static
      - media_data:/backend/media
      - nginx-data:/etc/nginx

    ports:
      - "8080:8080"

    depends_on:
      - backend

volumes:
  postgresql-data:
  static_data:
  media_data:
  nginx-data:
