# Generated by Django 4.1.6 on 2023-07-02 08:46

from django.db import migrations, models
import apps.accounts.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[apps.accounts.models.validators.NameRegexValidator()],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[apps.accounts.models.validators.NameRegexValidator()],
                verbose_name="last name",
            ),
        ),
    ]
