# Generated by Django 4.1.6 on 2023-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_adminprofile_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="study_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="num_courses",
            field=models.IntegerField(default=0),
        ),
    ]
