# Generated by Django 4.1.6 on 2023-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_adminprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='section',
            field=models.CharField(default=1, max_length=50, verbose_name='section'),
            preserve_default=False,
        ),
    ]
